name: "Run TODO to Issue"
on:
    push:
        paths:
            - '**.java'
# https://github.com/marketplace/actions/todo-to-issue

jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - name: "TODO to Issue"
              uses: "alstr/todo-to-issue-action@v4"
